Pregnancy/urls.py
from django.contrib import admin
from django.urls import path
from Main import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index', ),
    path('login/', views.login, name='login', ),
    path('logout/', views.logout, name='logout', ),
    path('user/list', views.user_list, name='userlist', ),
    path('logs/list', views.logs_list, name='logslist', ),
    path('export/', views.xml_export, name='export', ),
    path('card/<int:card_id>/show', views.card_show, name='card', ),
    path('card/<int:card_id>/download', views.xml_download, name='download', ),
    path('card/<int:card_id>/print', views.card_print, name='print', ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/forms.py
# -*- coding: utf-8 -*-

from django import forms
from datetime import date
from .choices import ROLE_CHOICES

######################################################################################################################


class FormUser(forms.Form):
    username = forms.CharField(
        label='Логин пользователя',
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control', 'placeholder': 'Введите логин пользователя', }
        ),
        required=True,
    )
    first_name = forms.CharField(
        label='Имя',
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control', 'placeholder': 'Введите имя пользователя', }
        ),
        required=True,
    )
    last_name = forms.CharField(
        label='Фамилия',
        widget=forms.TextInput(
            attrs={'type': 'text', 'class': 'form-control', 'placeholder': 'Введите фамилию пользователя', }
        ),
        required=True,
    )
    role = forms.ChoiceField(
        choices=ROLE_CHOICES,
        label='Роль пользователя',
        initial=0,
        widget=forms.Select(attrs={'class': 'custom-select'}),
        required=True,
    )
    passwd1 = forms.CharField(
        label='Пароль',
        widget=forms.TextInput(
            attrs={'type': 'password', 'class': 'form-control', 'autocomplete': 'off', }
        ),
        required=True,
    )
    passwd2 = forms.CharField(
        label='Подтверждение пароля',
        widget=forms.TextInput(
            attrs={'type': 'password', 'class': 'form-control', 'autocomplete': 'off', }
        ),
        required=True,
    )
    changepasswd1 = forms.CharField(
        label='Новый пароль',
        widget=forms.TextInput(
            attrs={'type': 'password', 'class': 'form-control', 'autocomplete': 'off', }
        ),
        required=True,
    )
    changepasswd2 = forms.CharField(
        label='Подтверждение нового пароля',
        widget=forms.TextInput(
            attrs={'type': 'password', 'class': 'form-control', 'autocomplete': 'off', }
        ),
        required=True,
    )

######################################################################################################################


class FormSearch(forms.Form):

    find = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
        required=False,
    )

######################################################################################################################


class FormUpload(forms.Form):

    files = forms.FileField(
        label='',
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file', 'multiple': True}),
        required=True,
    )

######################################################################################################################


class FormSelect(forms.Form):

    start_date = forms.DateField(
        label='Начальная дата',
        widget=forms.widgets.DateInput(attrs={'type': 'text', 'class': 'input-sm form-control', }),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d-%m-%Y'),
        required=True,
    )

    end_date = forms.DateField(
        label='Конечная дата',
        widget=forms.widgets.DateInput(attrs={'type': 'text', 'class': 'input-sm form-control',}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d-%m-%Y'),
        initial=date.today().__format__('%d.%m.%Y'),
        required=True,
    )

templates/base.html
{% load i18n %}{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block html_title %}Заголовок{% endblock %}</title>
    <link rel='shortcut icon' type='image/png' href='{% static "img/favicon.ico" %}'>
    <script src='{% static "js/jquery-3.4.1.min.js" %}'></script>
    <script src='{% static "js/bootstrap.min.js" %}'></script>
    <script src='{% static "fa/js/all.js" %}'></script>
    <link rel='stylesheet' href='{% static "css/bootstrap.min.css" %}' type='text/css' />
    {% block html_head %}{% endblock %}
</head>
<body>
{% block html_body_menu %}
    {% if request.user.is_authenticated %}
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="btn-toolbar" role="toolbar">
                <div class="btn-group mr-2" role="group">
                    <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">☰</button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <span class="dropdown-item"><strong>Здравствуйте, {% firstof user.get_full_name user.get_short_name user.get_username %}</strong></span>
                        {% if profile.role == 2 %}
                            <div class="dropdown-divider"></div>
                            <a href="{% url 'export' %}" class="dropdown-item">
                                <div class="row">
                                    <div class="col-auto mr-auto">Загрузка XML</div>
                                    <div class="col-auto mt-1 text-right"><i class="fas fa-folder-plus"></i></div>
                                </div>
                            </a>
                            <a href="{% url 'logslist' %}" class="dropdown-item">
                                <div class="row">
                                    <div class="col-auto mr-auto">Просмотр статистики</div>
                                    <div class="col-auto mt-1 text-right"><i class="far fa-chart-bar"></i></div>
                                </div>
                            </a>
                        {% endif %}
                        {% if profile.role == 1 or profile.role == 2 %}
                            <div class="dropdown-divider"></div>
                            <a href="{% url 'userlist' %}" class="dropdown-item">
                                <div class="row">
                                    <div class="col-auto mr-auto">Пользователи</div>
                                    <div class="col-auto mt-1 text-right"><i class="fas fa-user-friends"></i></div>
                                </div>
                            </a>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'logout' %}" class="dropdown-item">Выход</a>
                    </div>
                </div>
            </div>
            <a href="{% url 'index' %}" class="navbar-brand">&nbsp;Главная</a>
        </nav>
    {% endif %}
{% endblock %}
{% if toast %}
    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" style="position: absolute; bottom: 0; right: 10px;" data-delay="10000">
        <div class="toast-header">
            <strong class="mr-auto">Внимание</strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="toast-body">
            {{ toast }}
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.toast').toast('show');
        });
    </script>
{% endif %}
{% block html_body %}{% endblock %}
</body>
</html>

templates/card.html
<div class="mb-3">
    <h6>{{ card.organization }}</h6>
    <small class="form-text text-muted">Наименование медицинской организации, выдавшей справку</small>
</div>
<div class="mb-3">
    <h6>{{ card.number }}</h6>
    <small class="form-text text-muted">Номер спраки</small>
</div>
<div class="mb-3">
    <h6>{{ card.issue_date }}</h6>
    <small class="form-text text-muted">Дата выдачи справки</small>
</div>
<div class="row">
    <div class="col-md-4 mb-3">
        <h6>{{ card.resident.last_name }}</h6>
        <small class="form-text text-muted">Фамилия</small>
    </div>
    <div class="col-md-4 mb-3">
        <h6>{{ card.resident.first_name }}</h6>
        <small class="form-text text-muted">Имя</small>
    </div>
    <div class="col-md-4 mb-3">
        <h6>{{ card.resident.middle_name }}</h6>
        <small class="form-text text-muted">Отчество</small>
    </div>
</div>
<div class="mb-3">
    <h6>{{ card.resident.birthday}}</h6>
    <small class="form-text text-muted">Дата рождения</small>
</div>
<div class="mb-3">
    <h6>{{ snils }}</h6>
    <small class="form-text text-muted">СНИЛС</small>
</div>
<div class="mb-3">
    <h6>{{ card.address }}</h6>
    <small class="form-text text-muted">Адрес места жительства</small>
</div>
<div class="mb-3">
    <h6>{% if card.early_registration %}<i class="fas fa-check"></i>{% else %}<i class="fas fa-times"></i>{% endif %}</h6>
    <small class="form-text text-muted">Факт постановки на учет в ранние сроки беременности</small>
</div>
<div class="mb-3">
    <h6>{{ card.period_pregnancy }}</h6>
    <small class="form-text text-muted">Срок беременности</small>
</div>
<div class="mb-3">
    <h6>{{ card.doctor }}</h6>
    <small class="form-text text-muted">ФИО врача</small>
</div>
<div class="mb-3">
    <h6>{{ card.sign }}</h6>
    <small class="form-text text-muted">Поле для электронной подписи</small>
</div>
<div class="text-right">
    <a href="{% url 'download' card.id %}" class="btn btn-outline-primary"><i class="fas fa-download"></i> Скачать xml-файл</a>
    <a href="{% url 'print' card.id %}" class="btn btn-outline-secondary" target="_blank"><i class="fas fa-print"></i> Распечатать</a>
</div>

templates/export.html
{% extends "base.html" %}{% load static %}

{% block html_title %}Главная{% endblock %}
{% block html_head %}<link rel='stylesheet' href='{% static "css/main.css" %}' type='text/css' />{% endblock %}
{% block html_body %}
    <main role="main" class="container">
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h4 class="border-bottom border-gray pb-2 mb-0">Загрузка файлов XML в реестр справок о постановке на учет по беременности и родам:</h4>
            <form class="form-inline pt-3 border-bottom pb-3" method='post' action='' enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-auto mt-1">
                    <h5>Загрузить XML файлы:</h5>
                </div>
                <div class="col-auto mr-auto">
                        {{ form_upload.files }}
                </div>
                <div class="col-auto mr-0 text-right">
                    <button type="submit" class="btn btn-outline-primary">Загрузить</button>
                </div>
            </form>
            {% if successfully %}
                <h4>Успешно загружены фалйлы ({{ successfully|length }}):</h4>
                <ul>
                    {% for s in successfully %}
                        <li>{{ s }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </main>
{% endblock %}

templates/index.html
{% extends "base.html" %}{% load static %}

{% block html_title %}Главная{% endblock %}
{% block html_head %}
    <link rel='stylesheet' href='{% static "css/main.css" %}' type='text/css' />
    <script src='{% static "js/jquery.inputmask.js" %}'></script>
{% endblock %}
{% block html_body %}
    <main role="main" class="container">
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h4 class="border-bottom border-gray pb-2 mb-0">Поиск в реестре справок о постановке на учет по беременности и родам:</h4>
            <form method='post' class="mt-3" action='{% url 'index' %}'>
                {% csrf_token %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Введите СНИЛС:</span>
                    </div>
                    {{ form_search.find }}
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit" id="button-search"><i class="fas fa-search"></i> Поиск</button>
                    </div>
                </div>
            </form>
            {% if reference_list %}
                <h4 class="pb-2 sm-0">Результаты поиска:</h4>
                <div class="list-group">
                    {% for reference in reference_list %}
                        <button type="button" class="list-group-item list-group-item-action" onclick="ShowCard('{% url 'card' reference.id %}')">
                            Справка №{{ reference.number }} от {{ reference.issue_date }} выдана {{ reference.resident }}
                        </button>
                    {% endfor %}
                </div>
            {% endif %}
            {% if noresult %}
                <h4 class="pb-2 sm-0">Не найдено ни одного совпадаения.</h4>
            {% endif %}
        </div>
    </main>
    <!-- Окно отображения карточки -->
    <div class="modal fade" id="ModalCard" tabindex="-1" role="dialog" aria-labelledby="ModalCardTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content text-left">
                <div class="modal-header">
                    <h4 class="modal-title" id="ModalCardTitle">Справка о постановке на учет по беременности и родам:</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body" id="Card"></div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>

    <!-- /Окно создания нового пользователя -->
    <script type="text/javascript">
        $(document).ready(function(){
            $('#id_find').inputmask({mask: '999-999-999 99'});
        });
        function ShowCard(link) {

            $.get(link, function (data) {
                $('#Card').html(data);
            });
            $('#ModalCard').modal('show');
        }

    </script>
{% endblock %}

templates/login.html
{% extends "base.html" %}{% load static %}
{% block html_title %}Авторизация{% endblock %}
{% block html_head %}<link rel='stylesheet' href='{% static "css/floating-labels.css" %}' type='text/css' />{% endblock %}
{% block html_body %}
    {% if request.user.is_authenticated %}
        <meta http-equiv="REFRESH" content="0;url={% url 'index' %}">
    {% else %}
        <form class="form-signin" method="post" action="./">
            <input type="hidden" name="next" value="{{ next }}">
            <div class="text-center mb-4">
                <h1 class="h3 mb-3 font-weight-normal">Реестр справок о постановке на учет по беременности и родам</h1>
                <h4>Пожалуйста войдите:</h4>
                {% for message in messages %}
                    <div class="alert alert-danger" role="alert">{{ message }}</div>
                {% endfor %}
            </div>
            {% csrf_token %}
            <div class="form-label-group">
                <input type="text" id="id_username" name="username" class="form-control" placeholder="Логин" required autofocus>
                <label for="id_username">Логин</label>
            </div>
            <div class="form-label-group">
                <input type="password" id="id_password" name="password" class="form-control" placeholder="Пароль" required>
                <label for="id_password">Пароль</label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
            <p class="mt-5 mb-3 text-muted text-center">Министерство труда и социального развития Омской области</p>
        </form>
    {% endif %}
{% endblock %}

templates/logs.html
{% extends "base.html" %}{% load i18n %}{% load static %}

{% block html_title %}Главная{% endblock %}
{% block html_head %}
    <link rel='stylesheet' href='{% static "css/bootstrap-datepicker.min.css" %}' type='text/css' />
    <link rel='stylesheet' href='{% static "css/main.css" %}' type='text/css' />
    <script src='{% static "js/bootstrap-datepicker.min.js" %}'></script>
    <script src='{% static "js/locales/bootstrap-datepicker.ru.min.js" %}' charset='UTF-8'></script>
    {% if user_data %}
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
        <script type="text/javascript">
            google.charts.load('current', {'packages':['corechart']});
            google.charts.setOnLoadCallback(drawChart);
            function drawChart() {
                var data = google.visualization.arrayToDataTable({% autoescape off %}{{ user_data }}{% endautoescape %});
                var options = {
                    legend: 'none',
                    bar: { groupWidth: '75%' },
                    isStacked: true,
                    colors: ['#e0440e', '#e6693e', '#ec8f6e', '#f3b49f']
                };
                var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
                chart.draw(data, options);
            }
        </script>
    {% endif %}
{% endblock %}
{% block html_body %}
    <main role="main" class="container">
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h4 class="border-bottom border-gray pb-2 mb-0">Просмотр статистики использования реестра справок о постановке на учет по беременности и родам:</h4>
            <form method='post' class="mt-3" action='{% url 'logslist' %}'>
                {% csrf_token %}
                <div class="input-daterange input-group" id="datepicker">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Выберите диапазон дат:</span>
                    </div>
                    {{ form_select.start_date }}
                    {{ form_select.end_date }}
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit" id="button-search">Отобрать</button>
                    </div>
                </div>
                <!-- Инициализация виджета "Bootstrap datetimepicker" -->
                <script>
                    $('.input-daterange').datepicker({
                        format: "dd.mm.yyyy",
                        endDate: "+0d",
                        language: "ru",
                        todayBtn: "linked",
                        todayHighlight: true
                    });
                </script>
            </form>
            {% if user_data %}
                <h4>Статистика за период с {{ start_date }} по {{ end_date }}:</h4>
                <div id="chart_div"></div>
            {% endif %}
        </div>
    </main>
{% endblock %}

templates/print.html
{% extends "base.html" %}{% load static %}
{% block html_title %}Печать справки о постановке на учет по беременности и родам{% endblock %}
{% block html_body_menu %}{% endblock %}
{% block html_body %}
    <body onload="printit()">
    <script Language="Javascript">
        function printit(){
            if (window.print) {
                window.print();
                setTimeout(function () { window.close(); }, 100);
            } else {
                var WebBrowser = '<OBJECT ID="WebBrowser1" WIDTH=0 HEIGHT=0 CLASSID="CLSID:8856F961-340A-11D0-A96B-00C04FD705A2"></OBJECT>';
                document.body.insertAdjacentHTML('beforeEnd', WebBrowser);
                WebBrowser1.ExecWB(6, 2);//Use a 1 vs. a 2 for a prompting dialog box WebBrowser1.outerHTML = "";
            }
        }
    </script>
    <div class="mb-3">
        <h6>{{ card.organization }}</h6>
        <small class="form-text text-muted">Наименование медицинской организации, выдавшей справку</small>
    </div>
    <div class="mb-3">
        <h6>{{ card.number }}</h6>
        <small class="form-text text-muted">Номер спраки</small>
    </div>
    <div class="mb-3">
        <h6>{{ card.issue_date }}</h6>
        <small class="form-text text-muted">Дата выдачи справки</small>
    </div>
    <div class="row">
        <div class="col-md-4 mb-3">
            <h6>{{ card.resident.last_name }}</h6>
            <small class="form-text text-muted">Фамилия</small>
        </div>
        <div class="col-md-4 mb-3">
            <h6>{{ card.resident.first_name }}</h6>
            <small class="form-text text-muted">Имя</small>
        </div>
        <div class="col-md-4 mb-3">
            <h6>{{ card.resident.middle_name }}</h6>
            <small class="form-text text-muted">Отчество</small>
        </div>
    </div>
    <div class="mb-3">
        <h6>{{ card.resident.birthday}}</h6>
        <small class="form-text text-muted">Дата рождения</small>
    </div>
    <div class="mb-3">
        <h6>{{ snils }}</h6>
        <small class="form-text text-muted">СНИЛС</small>
    </div>
    <div class="mb-3">
        <h6>{{ card.address }}</h6>
        <small class="form-text text-muted">Адрес места жительства</small>
    </div>
    <div class="mb-3">
        <h6>{% if card.early_registration %}<i class="fas fa-check"></i>{% else %}<i class="fas fa-times"></i>{% endif %}</h6>
        <small class="form-text text-muted">Факт постановки на учет в ранние сроки беременности</small>
    </div>
    <div class="mb-3">
        <h6>{{ card.period_pregnancy }}</h6>
        <small class="form-text text-muted">Срок беременности</small>
    </div>
    <div class="mb-3">
        <h6>{{ card.doctor }}</h6>
        <small class="form-text text-muted">ФИО врача</small>
    </div>
    <div class="mb-3">
        <h6>{{ card.sign }}</h6>
        <small class="form-text text-muted">Поле для электронной подписи</small>
    </div>
{% endblock %}

templates/upload.html
{% extends "base.html" %}{% load static %}

{% block html_title %}Главная{% endblock %}
{% block html_head %}<link rel='stylesheet' href='{% static "css/main.css" %}' type='text/css' />{% endblock %}
{% block html_body %}
    <main role="main" class="container">
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h4 class="border-bottom border-gray pb-2 mb-0">Загрузка файлов XML в реестр справок о постановке на учет по беременности и родам:</h4>
            <form class="form-inline pt-3 border-bottom pb-3" method='post' action='' enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-auto mt-1">
                    <h5>Загрузить XML файлы:</h5>
                </div>
                <div class="col-auto mr-auto">
                        {{ form_upload.files }}
                </div>
                <div class="col-auto mr-0 text-right">
                    <button type="submit" class="btn btn-outline-primary">Загрузить</button>
                </div>
            </form>
            {% if successfully %}
                <h4>Успешно загружены фалйлы ({{ successfully|length }}):</h4>
                <ul>
                    {% for s in successfully %}
                        <li>{{ s }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </main>
{% endblock %}